# Guess the number generated by computer

import random

def guess(x):
    random_number = random.randint(1,x)
    guess = 0
    
    while guess!= random_number:
        guess = int(input(f"Guess a number between 1 and {x}: "))
        if guess<random_number:
            print("Try again.It is too low")
        elif guess>random_number:
            print("Try again.It is too high")
            
    
    print(f"Yay!you've correctly guessed the number {str(random_number)}. Congratz!!")
    

def main():
    x = int(input(f"You're going to guess a number 1 and x, where x>1.\nYou can determine this range by choosing x.\nChoose a number for x:  "))
    guess(x)
    
if __name__ == "__main__":
    main()